### ISSUE TITLE
rider status

### ISSUE THREAD

**Issue by vokalish** [Ogadai/zwift-mobile-api#14]
i want to get the full status x,y position, speed, power, etc.

if i execute the script in terminal .. there is an error

"UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Request failed with status code 404"

the little script

`var ZwiftAccount = require("zwift-mobile-api"); // don't edit this line

// settings you HAVE to edit are below this line //
var account = new ZwiftAccount("user", "password"); // put in your Zwift credentials between " " 
var playerId = "IknowMyID";  // put your Zwift ID between " " 
// end of settings you HAVE to edit // 

var world = account.getWorld(1); 

// Get the status of the specified rider
// (includes x,y position, speed, power, etc)
world.riderStatus(playerId).then(status => {
    console.log(status); // JSON of rider status
});`

**Comment by Ogadai** [comment]
Hi @vokalish 

Were you riding at the time? 404 ("Not Found") often means the rider is simply not currently in the world (i.e. not riding). If you are riding and then stop for a length of time, you will also be removed until you start riding again.

For testing purposes, you may find it helpful to use the rider id of someone who is riding (e.g. get the list of riders and pick one).

**Comment by vokalish** [comment]
yeah that's it. i could have come up with it myself....
i have still a question: which parameter shows me if I'm going up or down the mountain?
or are these data not available?

**Comment by Ogadai** [comment]
If you're looking incline (i.e. percent up or percent down), then I don't think that data is in the response. The best I've been able to come up with is calculating it from distance and altitude changes.

**Comment by vokalish** [comment]
this is a approach to get the percent up or percent down out. i'll give it a try.

**Comment by vokalish** [comment]
I think that I need all the parameters of x, y, altitude of the whole route and every meter to calculate the exact (LIVE)  percent up or percent down. That would be a bigger task.

**Comment by cagnulein** [comment]
> I think that I need all the parameters of x, y, altitude of the whole route and every meter to calculate the exact (LIVE) percent up or percent down. That would be a bigger task.

did you get inclination in some way?

**Comment by wiedmann** [comment]
Percent inclination is simply the difference in altitude divided by the horizontal distance covered. In three-dimensional terms:

```
inclination = ((alt - alt') / sqrt((x - x')^2 + (y - y')^2)) * 100
```

Where alt is the current value and alt' is the previous value. You can adjust your sampling and use interpolation if you want to say get the inclination over 10m instead of using a different length depending on the speed the rider is riding. Most likely that's overkill for Zwift, though.

**Comment by cagnulein** [comment]
> Percent inclination is simply the difference in altitude divided by the horizontal distance covered. In three-dimensional terms:
> 
> ```
> inclination = ((alt - alt') / sqrt((x - x')^2 + (y - y')^2)) * 100
> ```
> 
> Where alt is the current value and alt' is the previous value. You can adjust your sampling and use interpolation if you want to say get the inclination over 10m instead of using a different length depending on the speed the rider is riding. Most likely that's overkill for Zwift, though.

thanks @wiedmann so, you're saying that in the Zwift API you will have access to current altitude? I said so because i still don't have access to them so i don't know.

I've tried to write to the email on the readme of this project but the mail account is invalid now

**Comment by wiedmann** [comment]
Yes, you get x, y and z coordinates in each update. Also, this package is based on reverse engineering, not an official API. I'm not sure what you mean by "don't have access," but I don't think that that matters when using this package. All you would be doing is sniffing your own data packets and decoding them.
