### ISSUE TITLE
push speed to the server

### ISSUE THREAD

**Issue by nhoussay** [Ogadai/zwift-mobile-api#16]
Hello,

its maybe a stupid question, but do you have any idea how i could push speed and incline to zwift? I am asking the question because i am trying to build a bridge between iFit and Zwift and that would help if i could use an API (instead of broadcasting through BLE or ANT+).

Thanks

Nico

**Comment by Ogadai** [comment]
As far as I know it's not possible to do that via the API, but I am aware that other people have worked on ANT+ integrations.

If you're not already a member of the Zwift Coders Facebook group, why not request an invite and ask the question there?
https://www.facebook.com/groups/zwiftCoders

**Comment by nhoussay** [comment]
Thank you for your answer. Indeed i was going toward a BLE solution. I
think there must be something since the ZML can itself receive information
from a sensor and relay it to the Zwift Desktop. I will continue to dig.

I will ask the question in the FB group and will let you know if i find out
a solution.



Nicolas Houssay
+41 79 799 89 97
nicolas@houssay.net

**Comment by Ogadai** [comment]
@wiedmann did some work in [ZwiftAppConnection.js](../blob/master/src/ZwiftAppConnection.js) which might be a starting point.

It behaves like the ZML app, listening for a connection from Zwift (over the local network). Currently it only receives rider positions, so you'd need to figure out what messages to send and how to encode it.
