### ISSUE TITLE
Give RideOns

### ISSUE THREAD

**Issue by otakuu** [Ogadai/zwift-mobile-api#17]
An action to give RideOns would be nice:

- rideOn to single Rider
- rideOn to group

**Comment by Ogadai** [comment]
@otakuu When I saw this email come through, I thought you were submitting a pull request with RideOns implemented! Oh well :-/

I agree though - I've been meaning to implement a RideOn mechanism for a while now. It may happen this week if I get time.

Probably just for single riders though. You could use the Event APIs to get all the riders in an event category. If you just mean the group of riders who happen to be near you at the time, then I don't know how to do that.

**Comment by Ogadai** [comment]
Turned out to be pretty easy. Check out `profile.giveRideOn(otherRiderId, activityId);` in the documentation.
