### ISSUE TITLE
Request failed with status code 403

### ISSUE THREAD

**Issue by paixaop** [Ogadai/zwift-mobile-api#22]
Hi when trying to get world like in the example code 

```
var ZwiftAccount = require("zwift-mobile-api"); 
var account = new ZwiftAccount("my_user", "my_passwd"); 

var world = account.getWorld(1);  
world.riders().then(riders => {
    console.log(riders); // JSON array of all riders currently riding
}, (error) => {
    console.log('Error!');
    console.error(error);
});
```

I get `Request failed with status code 403` error. 
What am i doing wrong? Thanks for the help!

**Comment by Ogadai** [comment]
Hi @paixaop 

Apologies, but since the GDPR changes, you now need a special developer account. Please see the updated [ReadMe](https://github.com/Ogadai/zwift-mobile-api) for details.
